//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Base_kafedra_try3
{
    using System;
    using System.Collections.Generic;
    
    public partial class disciplini
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disciplini()
        {
            this.vedomosti = new HashSet<vedomosti>();
            this.vedomosti1 = new HashSet<vedomosti>();
        }
    
        public long kod_disciplini { get; set; }
        public long kod_kafedri { get; set; }
        public string Name_discip { get; set; }
        public Nullable<int> Raschasovka { get; set; }
        public string Kontrol_form { get; set; }
    
        public virtual kafedra kafedra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vedomosti> vedomosti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vedomosti> vedomosti1 { get; set; }
    }
}
