//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Base_kafedra_try3
{
    using System;
    using System.Collections.Generic;
    
    public partial class kafedra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kafedra()
        {
            this.disciplini = new HashSet<disciplini>();
            this.gruppi = new HashSet<gruppi>();
            this.Prepodovateli = new HashSet<Prepodovateli>();
        }
    
        public long kod_kafedri { get; set; }
        public long kod_fakulteta { get; set; }
        public string Name_kafedri { get; set; }
        public string FIO { get; set; }
        public string Nom_komnati_kafedri { get; set; }
        public string Telefon_kafedri { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disciplini> disciplini { get; set; }
        public virtual fakulteti fakulteti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gruppi> gruppi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prepodovateli> Prepodovateli { get; set; }
    }
}
