//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Base_kafedra_try3
{
    using System;
    using System.Collections.Generic;
    
    public partial class podchin_tablica_vedomosti
    {
        public long kod_pod_vedomosti { get; set; }
        public long kod_vedomosti { get; set; }
        public long kod_studenta { get; set; }
        public Nullable<int> Ocenka { get; set; }
    
        public virtual vedomosti vedomosti { get; set; }
    }
}
